include:
  - board: seeeduino_xiao_ble
    shield: roBa_Dongle
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_R
    #snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_L
  - board: nice_nano_v2
    shield: ploopy_trackball_R
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
