include:
  - board: seeeduino_xiao_ble
    shield: roBa_Dongle
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_R
    #snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_L
  - board: seeeduino_xiao_ble
    shield: settings_reset
